name: quiz_server
description: A Dart console application for a multiplayer quiz game server.
version: 1.0.0
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  async: ^2.8.2
  collection: ^1.15.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
